export const hotelLists = [
  {
    id: 1,
    title: "Hotel Annapurna",
    address: "Durbarmarg, Kathmandu",
    rating: 4.5,
    discountPercent: 10,
    price: 3000,
    imgUrl: "/hotel-room-1.jpg",
  },
  {
    id: 2,
    title: "Mountain Paradise",
    address: "Thamel, Kathmandu",
    rating: 4.7,
    discountPercent: 15,
    price: 4000,
    imgUrl: "/hotel-room-2.jpg",
  },
  {
    id: 3,
    title: "City View Hotel",
    address: "New Road, Kathmandu",
    rating: 4.2,
    discountPercent: 5,
    price: 2500,
    imgUrl: "/hotel-room-3.jpg",
  },
  {
    id: 4,
    title: "Lakeside Resort",
    address: "Pokhara, Nepal",
    rating: 4.8,
    discountPercent: 20,
    price: 5000,
    imgUrl: "/hotel-room-4.jpg",
  },
  {
    id: 5,
    title: "Heritage Hotel",
    address: "Patan, Nepal",
    rating: 4.3,
    discountPercent: 10,
    price: 3200,
    imgUrl: "/hotel-room-1.jpg",
  },
  {
    id: 6,
    title: "Royal Palace Hotel",
    address: "Bhaktapur, Nepal",
    rating: 4.6,
    discountPercent: 12,
    price: 3600,
    imgUrl: "/hotel-room-2.jpg",
  },
  {
    id: 7,
    title: "Luxury Stay",
    address: "Nagpokhari, Kathmandu",
    rating: 4.9,
    discountPercent: 18,
    price: 6000,
    imgUrl: "/hotel-room-3.jpg",
  },
  {
    id: 8,
    title: "Budget Inn",
    address: "Lalitpur, Nepal",
    rating: 3.8,
    discountPercent: 5,
    price: 1500,
    imgUrl: "/hotel-room-4.jpg",
  },
];
